name: learn-workflow
on: push
jobs:
  job1:
    name: first-job
    runs-on: ubuntu-latest
    steps:
      - name: first step in first job
        uses: actions/checkout@v2
      - name: second step in first job
        run: echo "hello world"
  job2:
    name: second-job
    runs-on: windows-latest
    steps:
      - name: first step in second job
        uses: actions/checkout@v2
      - name: second step in second job
        run: ls